// powered by xtr softwares
const roasts = [
"You’re not dumb by accident—it’s clearly sustained effort.",
"Your intellect is theoretical, like faster-than-light travel.",
"You don’t lack depth; you actively repel it.",
"You make ignorance look methodical.",
"Your brain treats logic as a hostile foreign concept.",
"You have the confidence of someone who has never checked their facts.",
"You’re not wrong occasionally—you’re wrong consistently.",
"Your thinking process is more of a suggestion.",
"You confuse being loud with being right.",
"You are living proof that consciousness is optional.",

"You don’t misunderstand complexity—you misunderstand basics.",
"Your thoughts have the structural integrity of wet paper.",
"You argue like evidence personally offended you.",
"You don’t think critically—you think aggressively.",
"You treat facts like optional DLC.",
"You’re not anti-intellectual; you’re post-intellectual.",
"You make bad conclusions with academic enthusiasm.",
"Your reasoning collapses under light scrutiny.",
"You weaponize confidence to compensate for understanding.",
"You don’t debate ideas—you mug them.",

"You’re not shallow—you’re aggressively hollow.",
"You bring nothing to discussions except momentum.",
"You have the mental agility of a parked truck.",
"You treat nuance like it owes you money.",
"You don’t process information—you mangle it.",
"Your opinions arrive pre-wrong.",
"You mistake repetition for proof.",
"You are confidently incorrect in high definition.",
"You don’t learn—you double down.",
"You argue like truth is negotiable.",

"You have the intellect of a philosophical dead end.",
"You don’t lack awareness—you evade it.",
"You’re not uninformed—you’re information-resistant.",
"You approach thinking like it’s a personal insult.",
"You reduce complex ideas to noise.",
"You don’t misunderstand context—you delete it.",
"You have conclusions in search of reasoning.",
"You make assumptions like they’re peer-reviewed.",
"You confuse certainty with intelligence.",
"You’re not a skeptic—you’re just dismissive.",

"You bring chaos disguised as confidence.",
"You don’t reason—you ricochet.",
"You speak with authority borrowed from nowhere.",
"You treat ignorance as a personality trait.",
"You have answers with no questions attached.",
"You don’t examine beliefs—you guard them.",
"You turn discussions into cautionary tales.",
"You mistake stubbornness for principle.",
"You think loudly enough to drown out thought.",
"You’re the final form of intellectual complacency.",

"You don’t challenge ideas—you bruise them.",
"You make bad logic look intentional.",
"You approach thinking like it’s optional homework.",
"You have the self-awareness of an unlabelled experiment.",
"You don’t debate—you survive conversations.",
"You bring certainty where curiosity should be.",
"You mistake instinct for insight.",
"You speak in conclusions, not arguments.",
"You don’t reason forward—you backfill excuses.",
"You have opinions that outpace comprehension.",

"You don’t evolve intellectually—you ossify.",
"You treat complexity like an inconvenience.",
"You argue with the confidence of a broken model.",
"You don’t seek truth—you seek validation.",
"You’re not misunderstood; you’re overestimated.",
"You confuse skepticism with cynicism.",
"You talk like evidence is a personal attack.",
"You don’t refine ideas—you bludgeon them.",
"You mistake volume for substance.",
"You are the intellectual equivalent of noise.",

"You don’t lack intelligence—you misallocate it.",
"You make thinking look hazardous.",
"You approach logic like it’s a conspiracy.",
"You don’t analyze—you assert.",
"You have conclusions without premises.",
"You treat correction as betrayal.",
"You don’t grow mentally—you calcify.",
"You mistake dismissal for dominance.",
"You argue like being wrong is a lifestyle.",
"You are what happens when confidence outruns competence.",

"You don’t misunderstand reality—you reinterpret it badly.",
"You have the critical thinking skills of a rumor.",
"You don’t explore ideas—you occupy them.",
"You turn discussions into endurance tests.",
"You mistake reaction for reflection.",
"You don’t reason—you posture.",
"You have beliefs on life support.",
"You speak like thinking is outsourced.",
"You don’t add insight—you add drag.",
"You are a walking footnote titled ‘why this failed.’",

"You don’t process nuance—you incinerate it.",
"You treat knowledge like it’s optional décor.",
"You don’t reason from evidence—you decorate opinions with it.",
"You have the intellectual rigor of a vibes-based argument.",
"You don’t debate ideas—you test patience.",
"You mistake certainty for clarity.",
"You are intellectually loud, not intellectually present.",
"You don’t think deeply—you sink shallowly.",
"You don’t engage with ideas—you collide with them.",
"You are the nuclear option of bad reasoning."
];
export default roasts;
